- stories_link:
    url: 'http://seercap.com/people'
    selectors:
      base_links:
        selector: 'article[class*=people] section[itemprop*=articleBody] a'
        return_type: 'list'
        attr: 'href'
      Designation:
        selector: 'h1[itemprop*=headline] + p'
        return_type: 'list'
    bio_selectors:
      base_url: 'http://seercap.com/people'
      selectors:
        Name: 'article[class*=people] .post-title'
        Bio: 'section[itemprop*=articleBody] p'
        Title: '{{ Designation }}'

- stories_link:
    url: 'https://www.naviscapital.com/web/navis/investment-committee-members'
    selectors:
      Data:
        selector: '.journal-content-article *'
        attr: 'tags'
    function:
      func_name: 'get_from_naviscapital'
      Name: 'Name'
      Bio: 'Bio'
      Title: 'Title'

- stories_link:
    url: 'http://www.jll.com/about/board-of-directors-and-governance'
    selectors:
      Data:
        selector: '#ctl00_PlaceHolderMain_DeviceChannelAuthoringControl_ctl00_PageContentField__ControlWrapper_RichHtmlField *'
        attr: 'tags'
    function:
      func_name: 'get_from_jll_bod'
      Name: 'Name'
      Bio: 'Bio'
      Title: 'Title'
      Division: 'Division'

- stories_link:
    url: 'http://www.jll.com/about/global-management'
    selectors:
      base_links:
        selector: 'table tr td a'
        return_type: 'list'
        attr: 'href'
      page_title:
        selector: '#DeltaPlaceHolderPageTitleInTitleArea'
        return_type: 'list'
    bio_selectors:
      selectors:
        Name: '.profile h2'
        Bio: '.mainedit3 p'
        Title: '.profile h3'
        Division: '{{ page_title }}'
        Email: '.profile .email a'


- stories_link:
    url: 'http://www.jll.com/about/additional-corporate-officers'
    selectors:
      Data:
        selector: 'table tr td'
        attr: 'tags'
    function:
      func_name: 'get_from_jll_corporate'
      Name: 'Name'
      Title: 'Title'
      Division: 'Division'


- stories_link:
    url: 'https://www.vistra.com/about-us/senior_management'
    selectors:
      base_links:
        selector: '.management-board .f_1 .people-grid-title a'
        return_type: 'list'
        attr: 'href'
    bio_selectors:
      base_url: 'https://www.vistra.com'
      selectors:
        Name: '.profile-content h1 .field-item'
        Bio: '.bio .field-item p'
        Title: '.profile-content h1 + h2'
        Division: '{% Executive Committee %}'
        Phone-1: '.profile-content .tel'
        Phone-2: '.profile-content .mobile'
        Email: '.email'

- stories_link:
    url: 'https://www.vistra.com/about-us/senior_management'
    selectors:
      base_links:
        selector: '.management-board .f_2 .people-grid-title a'
        return_type: 'list'
        attr: 'href'
    bio_selectors:
      base_url: 'https://www.vistra.com'
      selectors:
        Name: '.profile-content h1 .field-item'
        Bio: '.bio .field-item p'
        Title: '.profile-content h1 + h2'
        Division: '{% Private Clients %}'
        Phone-1: '.profile-content .tel'
        Phone-2: '.profile-content .mobile'
        Email: '.email'

- stories_link:
    url: 'https://www.vistra.com/about-us/senior_management'
    selectors:
      base_links:
        selector: '.management-board .f_3 .people-grid-title a'
        return_type: 'list'
        attr: 'href'
    bio_selectors:
      base_url: 'https://www.vistra.com'
      selectors:
        Name: '.profile-content h1 .field-item'
        Bio: '.bio .field-item p'
        Title: '.profile-content h1 + h2'
        Division: '{% Company Formation %}'
        Phone-1: '.profile-content .tel'
        Phone-2: '.profile-content .mobile'
        Email: '.email'

- stories_link:
    url: 'https://www.vistra.com/about-us/senior_management'
    selectors:
      base_links:
        selector: '.management-board .f_4 .people-grid-title a'
        return_type: 'list'
        attr: 'href'
    bio_selectors:
      base_url: 'https://www.vistra.com'
      selectors:
        Name: '.profile-content h1 .field-item'
        Bio: '.bio .field-item p'
        Title: '.profile-content h1 + h2'
        Division: '{% International Expansion %}'
        Phone-1: '.profile-content .tel'
        Phone-2: '.profile-content .mobile'
        Email: '.email'

- stories_link:
    url: 'https://www.vistra.com/about-us/senior_management'
    selectors:
      base_links:
        selector: '.management-board .f_5 .people-grid-title a'
        return_type: 'list'
        attr: 'href'
    bio_selectors:
      base_url: 'https://www.vistra.com'
      selectors:
        Name: '.profile-content h1 .field-item'
        Bio: '.bio .field-item p'
        Title: '.profile-content h1 + h2'
        Division: '{% Corporate Clients %}'
        Phone-1: '.profile-content .tel'
        Phone-2: '.profile-content .mobile'
        Email: '.email'

- stories_link:
    url: 'https://www.vistra.com/about-us/senior_management'
    selectors:
      base_links:
        selector: '.management-board .f_6 .people-grid-title a'
        return_type: 'list'
        attr: 'href'
    bio_selectors:
      base_url: 'https://www.vistra.com'
      selectors:
        Name: '.profile-content h1 .field-item'
        Bio: '.bio .field-item p'
        Title: '.profile-content h1 + h2'
        Division: '{% Alternative Investments %}'
        Phone-1: '.profile-content .tel'
        Phone-2: '.profile-content .mobile'
        Email: '.email'

- stories_link:
    url: 'https://www.vistra.com/about-us/senior_management'
    selectors:
      base_links:
        selector: '.management-board .f_7 .people-grid-title a'
        return_type: 'list'
        attr: 'href'
    bio_selectors:
      base_url: 'https://www.vistra.com'
      selectors:
        Name: '.profile-content h1 .field-item'
        Bio: '.bio .field-item p'
        Title: '.profile-content h1 + h2'
        Division: '{% Group Functions %}'        
        Phone-1: '.profile-content .tel'
        Phone-2: '.profile-content .mobile'
        Email: '.email'
